version: '3'

services:
  nodered-slim:
    build:
      context: .
      dockerfile: Dockerfile
    image: wutadmin/node-red-slim:latest
    container_name: slim-red
    env_file:
      - .env.prod
    ports:
      - "1889:1880"
